apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    app: {{ .Values.web.label.name }}
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: {{ .Values.web.name }}
  selector:
    app: {{ .Values.web.label.name }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.label.name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: {{ .Values.api.label.name }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.label.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: {{ .Values.db.name }}
  selector:
    app: {{ .Values.db.label.name }}
  clusterIP: None
